#!/bin/sh
### BEGIN INIT INFO
# Provides:          wondershaper
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

cmd_start="wondershaper -p"
cmd_stop="wondershaper -p -c"

name=`basename $0`
stdout_log="/var/log/$name.log"
stderr_log="/var/log/$name.err"

is_running() {
    status_msg=`wondershaper -p -s | grep qdisc`
    [ "$status_msg" != "" ] > /dev/null 2>&1
}

case "$1" in
    start)
    if is_running; then
        $0 stop
    fi
    echo "Starting $name"
    $cmd_start >> "$stdout_log" 2>> "$stderr_log"
    if ! is_running; then
        echo "Unable to start, see $stdout_log and $stderr_log"
        exit 1
    fi
    echo "Started"
    ;;
    stop)
    if is_running; then
        echo -n "Stopping $name.."
        $cmd_stop
        for i in {1..10}
        do
            if ! is_running; then
                break
            fi

            echo -n "."
            sleep 1
        done
        echo

        if is_running; then
            echo "Not stopped; may still be shutting down or shutdown may have failed"
            exit 1
        else
            echo "Stopped"
        fi
    else
        echo "Not running"
    fi
    ;;
    restart)
    $0 stop
    if is_running; then
        echo "Unable to stop, will not attempt to start"
        exit 1
    fi
    $0 start
    ;;
    status)
    if is_running; then
        echo "Running"
    else
        echo "Stopped"
        exit 1
    fi
    ;;
    *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
